import pygame

#Images :
icon = pygame.image.load("assets/icon.png")
bouton_play = pygame.image.load("assets/bouton_play.png")
bouton_play = pygame.transform.scale(bouton_play, (700, 500))
bouton_option = pygame.image.load("assets/bouton_option.png")
bouton_option = pygame.transform.scale(bouton_option, (700, 500))
bouton_exit = pygame.image.load("assets/bouton_exit.png")
bouton_exit = pygame.transform.scale(bouton_exit, (700, 500))
fond_ecran = pygame.image.load("assets/menu.png")
son = pygame.image.load("assets/son.png")
son = pygame.transform.scale(son, (150, 150))
pas_son = pygame.image.load("assets/pas_son.png")
pas_son = pygame.transform.scale(pas_son, (150, 150))
fond_ecran_option = pygame.image.load("assets/menu_option.png")
fond_ecran_option = pygame.transform.scale(fond_ecran_option, (1600, 900))
fond_ecran_commands = pygame.image.load("assets/menu_commands.png")
bouton_retour_menu = pygame.image.load("assets/bouton_retour.png")
bouton_retour_menu = pygame.transform.scale(bouton_retour_menu, (500, 300))
bouton_commands = pygame.image.load("assets/commands.png")
bouton_commands = pygame.transform.scale(bouton_commands, (300, 300))
bouton_retour_option = pygame.image.load("assets/bouton_retour.png")
bouton_retour_option = pygame.transform.scale(bouton_retour_option, (500, 300))
bulle = pygame.image.load("assets/bulle.png")
bulle = pygame.transform.scale(bulle, (300, 300))
bouton_help = pygame.image.load("assets/bouton_help.png")
bouton_help = pygame.transform.scale(bouton_help, (200, 200))
rond_credits = pygame.image.load("assets/rond_credits.png")
rond_credits = pygame.transform.scale(rond_credits, (700, 700))
fond_ecran_help = pygame.image.load("assets/menu_help.jpg")
fond_ecran_help = pygame.transform.scale(fond_ecran_help, (1600, 900))
bouton_retour_help_option = pygame.image.load("assets/bouton_retour.png")
bouton_retour_help_option = pygame.transform.scale(bouton_retour_help_option, (500, 300))

#Maps :
map1 = pygame.image.load("assets/map.jpg")